platform:ios, '12.0'

# github 官方 pod 源
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "MXOCDemo" do
  
  pod 'CryptoSwift', '~> 1.4.0'
  pod 'MXBleProvision', :git => 'https://github.com/MXCHIP/MXBleProvision.git'

end


pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
         end
    end
  end
end
